### ISSUE TITLE
Version Tags / Releases

### ISSUE THREAD

**Issue by hashworks** [filiphanes/fts-elastic#14]
Could you publish version tags or releases? I would like to push this to the Arch Linux community repository, but I'll need versions for that.

**Comment by filiphanes** [comment]
https://github.com/filiphanes/fts-elastic/releases/tag/1.0.0
is it ok?

**Comment by Bubu** [comment]
@hashworks FYI, I packaged this in AUR a while ago: https://aur.archlinux.org/packages/dovecot-fts-elastic/

I'd be happy if this moves to community though :).

**Comment by hashworks** [comment]
@filiphanes Yes, thank you.
@Bubu Yup, I might reuse that :)
