### ISSUE TITLE
wildcard search support

### ISSUE THREAD

**Issue by purjopirjo** [filiphanes/fts-elastic#16]
https://github.com/filiphanes/fts-elastic/blob/master/src/fts-backend-elastic.c
Trying to figure out what to modify to enable wildcard searches like this:
`curl -X GET "http://127.0.0.1:9200/m/_search?pretty" -H 'Content-Type: application/json' -d '
{
  "query": {
    "bool": {
      "filter": [
        {"term": {"user": "filip.hanes@example.com"}}
      ],
      "must": [{
        "wildcard": {
          "body": "searchstrin*"
        }
      }]
    }
  },
  "size": 100
}'`
Or is it bad idea, what you think? (ES7)
Multiple fields aren't supported with wildcard search, in this example its only "body", would need to iterate fields (subject, from, to etc) somehow maybe..

**Comment by filiphanes** [comment]
does IMAP or Dovecot support wildcard search?
if not you would want to use your syntax with prefix* and translate it to elastic wildcard query, and that would not be compatible with other search backends

**Comment by purjopirjo** [comment]
im working with iredmail stack here (debian10), imap would be dovecot 2.3.4.1 with fts-elastic plugin installed. Searches are fast now but only with full words, so need to tweak something to get results from partial search strings too. Im testing searches from roundcube webmail and had output in elasticsearch_index_search_slowlog.log(0ms) with multi_match format. Thats why im here wondering how to make queries work with wildcard format instead :-D

**Comment by filiphanes** [comment]
If you want to type "searchstrin" in roundcube searchfield and want to find emails containing word "searchstring" or partial phone numbers etc. then you need to change analyzers/tokenizers to index tokens for prefixes in elastic mapping.

If you want to type "searchstri*" and want to find "searchstring" only if there is asterix then some code would need to parse this asterix syntax and translate it to backend. I don't know that dovecot/imap would support this syntax. If I would implement it only in fts-elastic then fts-solr or native dovecot fts would not work the same way.

**Comment by purjopirjo** [comment]
Ok, thank you for pointing me into right direction!
So i'll tweak elastic7-schema.json then(?), maybe it can be changed in package with "searchstrin" support? Or does it take too much disk space and thus left to user decide?

**Comment by filiphanes** [comment]
yes, you need to tweak elastic7-schema.json,
Provided elastic mapping is trying to give user same experience as with default dovecot fts - without support for prefixes, stemming, phone, email, url etc.
But yes, there could be at least notice in README that support for prefixes is not implemented a needs to be tweaked in elastic mapping.
