### ISSUE TITLE
Date format errors in elasticsearch: failed to parse field [date] of type [date]

### ISSUE THREAD

**Issue by rpv-tomsk** [filiphanes/fts-elastic#29]
Can you please assist with issue I see in logs:

```
{"index":
{"_index":"m","_id":"23510/4f8ae61ae1902151d6120000bb28466e/user@domain.tld","status":400,
"error":{
    "type":"document_parsing_exception",
    "reason":"[1:338] failed to parse field [date] of type [date] in document with id '23510/4f8ae61ae1902151d6120000bb28466e/user@domain.tld'. Preview of field's value: 'Wed, 18 Jan 2023 13:00:20 +0500 (+05)'",
    "caused_by":{
        "type":"illegal_argument_exception",
        "reason":"failed to parse date field [Wed, 18 Jan 2023 13:00:20 +0500 (+05)] with format [[EEE, ][ ]d MMM yyyy HH:mm:ss[ Z][ (z)]]",
        "caused_by":{
            "type":"date_time_parse_exception","reason":"Text 'Wed, 18 Jan 2023 13:00:20 +0500 (+05)' could not be parsed, unparsed text found at index 31"
        }
    }
}
}},
```
"Index 31" is "Thu,  2 Sep 2021 16:48:39 +050**0** (+05)"

I use `elasticsearch-8.8.1` and `elastic7-schema.json` from repo.

References: #7 #8

**Comment by filiphanes** [comment]
Index 31 is at first brace `(`.

According to Java DateTimeFormatter documentation https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/time/format/DateTimeFormatter.html
lower case z matches **time-zone name**, not a number offset.

You should fix your date values or change elastic schema date pattern to `[[EEE, ][ ]d MMM yyyy HH:mm:ss[ Z][ (x)]]`

**Comment by filiphanes** [comment]
ok, maybe you have that date in email header, but according to RFC2822 email date has this format https://www.rfc-editor.org/rfc/rfc2822#page-14
Which don't match with your value `Wed, 18 Jan 2023 13:00:20 +0500 (+05)`.
