### ISSUE TITLE
Compatibility with Opensearch?

### ISSUE THREAD

**Issue by HLFH** [filiphanes/fts-elastic#31]
[opensearch](https://opensearch.org/)

An Elasticsearch fork.
Officially supported on Arch Linux.

https://archlinux.org/packages/extra/x86_64/opensearch/

I am using `fts-elastic`, it's great. As I was interested to migrate from Elasticsearch to Opensearch, I wanted to know if `fts-elastic` is compatible.

**Comment by hashworks** [comment]
I'm using this with OpenSearch, it works fine.

**Comment by filiphanes** [comment]
since opensearch is fork of elastic and will use same api, it will be compatible.

**Comment by hashworks** [comment]
I think newer elastic APIs will not work on OpenSearch. I've seen [stuff that doesn't work with it](https://github.com/nextcloud/fulltextsearch_elasticsearch/issues/271#issuecomment-1699594140), so I wouldn't be so sure about that.
