### ISSUE TITLE
Build fails with dovecot 2.3.21

### ISSUE THREAD

**Issue by muhviehstah** [filiphanes/fts-elastic#33]
the plugin got build errors with dovecot 2.3.21 :

`fts-elastic-plugin.c: In function 'fts_elastic_mail_user_deinit':
fts-elastic-plugin.c:82:26: error: passing argument 1 of 'fts_mail_user_deinit' from incompatible pointer type [-Wincompatible-pointer-types]
   82 |     fts_mail_user_deinit(user);
      |                          ^~~~
      |                          |
      |                          struct mail_user *
/usr/include/dovecot/fts-user.h:23:45: note: expected 'struct mail_user *' but argument is of type 'struct mail_user *'
   23 | void fts_mail_user_deinit(struct mail_user *user);
      |                           ~~~~~~~~~~~~~~~~~~^~~~
fts-elastic-plugin.c: In function 'fts_elastic_mail_user_create':
fts-elastic-plugin.c:105:28: error: passing argument 1 of 'fts_mail_user_init' from incompatible pointer type [-Wincompatible-pointer-types]
  105 |     if (fts_mail_user_init(user, FALSE, &error) < 0) {
      |                            ^~~~
      |                            |
      |                            struct mail_user *
/usr/include/dovecot/fts-user.h:21:42: note: expected 'struct mail_user *' but argument is of type 'struct mail_user *'
   21 | int fts_mail_user_init(struct mail_user *user, bool initialize_libfts,
      |                        ~~~~~~~~~~~~~~~~~~^~~~
make[2]: *** [Makefile:478: fts-elastic-plugin.lo] Error 1
make[2]: *** Waiting for unfinished jobs...`

**Comment by hashworks** [comment]
Builds successfully on my end with 2.3.21.1 (note the `.1` suffix).

**Comment by muhviehstah** [comment]
not here on arch Linux, maybe you can give me some details of your build env to double check?

compiler, flags etc

**Comment by hashworks** [comment]
https://gitlab.archlinux.org/archlinux/packaging/packages/dovecot-fts-elastic/-/blob/main/PKGBUILD

```
git clone https://gitlab.archlinux.org/archlinux/packaging/packages/dovecot-fts-elastic.git
cd dovecot-fts-elastic
pkgctl build
```

Note that it uses a patch from the master branch https://github.com/filiphanes/fts-elastic/commit/411d711b4a587f3124d0fcfd8c6fd0a6bce92cc5

**Comment by muhviehstah** [comment]
thank you, missed the patch from master branch
