### ISSUE TITLE
No "date" field in pushed document

### ISSUE THREAD

**Issue by thorzh** [filiphanes/fts-elastic#6]
There is no "date" field in the pushed documents, and it's not in _source either.  Elasticsearch version 7.6.0, and index mapping is created with the included elastic7-schema.json file.  Is this supposed to be the case or have I missed something?  Thanks.

**Comment by filiphanes** [comment]
thank you, I will check it

**Comment by filiphanes** [comment]
added Date to wanted field, you can check if it works for you

**Comment by thorzh** [comment]
Thanks for working on this.  However there is a compile error now

```
fts-backend-elastic.c:27:20: error: static declaration of ‘json_hex_chars’ follows non-static declaration
 static const char *json_hex_chars = "0123456789abcdefABCDEF";
                    ^~~~~~~~~~~~~~
In file included from /usr/include/json-c/linkhash.h:16:0,
                 from /usr/include/json-c/json.h:22,
                 from elastic-connection.h:7,
                 from fts-backend-elastic.c:23:
/usr/include/json-c/json_object.h:65:20: note: previous declaration of ‘json_hex_chars’ was here
 extern const char *json_hex_chars;
                    ^~~~~~~~~~~~~~
Makefile:467: recipe for target 'fts-backend-elastic.lo' failed
```

**Comment by filiphanes** [comment]
interesting, I have compiled it without problem, try now, already renamed that variable

**Comment by thorzh** [comment]
Thanks, all good now.
