### ISSUE TITLE
date format errors in elasticsearch

### ISSUE THREAD

**Issue by Bubu** [filiphanes/fts-elastic#7]
I wanted to set this up using elasticsearch 7.6.1 following your readme.

Indexing worked fine whenever I want to search via imap, I get no results and elasticsearch puts a lot of java exceptions amounting to 

> Caused by: java.lang.IllegalArgumentException: failed to parse date field [Mon, 20 Apr 2020 15:00:07 -0400] with format [EEE, d LLL yyyy HH:mm:ss Z||yyyy-MM-dd HH:mm:ss||yyyy-MM-dd]

in the log.

Any idea what might be going wrong, or how I'd fix that? 

(The format looks correct to me?)

**Comment by filiphanes** [comment]
yes, the format string looks good, but probably is not:
here is doc: https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html
and elastic 7 uses this Java formatter https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html for custom date mappings
here can be tested java formats https://javadevtools.com/datetimeformatter
and it looks like we need to change LLL to MMM it the format string

please try it, and when it works, I will update recommended mapping
thanks

**Comment by Bubu** [comment]
Everything works now! :-)
